version: "3.7"
services:

  python-cli:
    container_name: grasian-cite-python-cli
    command: python launcher.py
    build:
      context: ./
      dockerfile: ./docker/production/python-cli.docker
    env_file:
      - ./.env