version: "3.7"
services:

  python-cli:
    container_name: grasian-cite-python-cli
    image: romanr2/grasian-cite-python-cli:v1.0.0
    restart: always
    command: python launcher.py
    env_file:
      - ./.env